### ISSUE TITLE
Area field should use a "hidden" value to build the query

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#15]
The "area" filed (in patent database corresponding to Cooperative Patent Classification, CPC) is showing some values in the combo box. The query field is currently using the same value that is shown in the field. i.e. : If you choose "Random or pseudo-random number generators" the corresponding query field is tecarea=Random or pseudo-random number generators
Instead of that, we should create the query using a code that rapresents "Random or pseudo-random number generators". ie.: If "Random or pseudo-random number generators" has a "hidden value" of "G06F7/58" the query will be "tecarea=G06F7/58

**Comment by dudi2022** [comment]
I’m going to need a second explanation to understand what you would like
here - I half understand!

**Comment by marco-svitol** [comment]
Sure. Meanwhile you may want to have a look at a project we realized some time ago:
https://github.com/marco-svitol/forexconsolefe

In there, we used that method with the "pos" vairable.
Take a look at file Dashboard.js:
https://github.com/marco-svitol/forexconsolefe/blob/master/src/components/Dashboard/Dashboard.js

Line 279:
![image](https://user-images.githubusercontent.com/62987024/216811387-d11dfada-f867-4a19-a001-1b035897a1f2.png)

**Comment by dudi2022** [comment]
okay, thank you. maybe let me take some time to work on these issues - if I have any questions I will let you know here - no need to call this afternoon unless you would like to :-)

**Comment by marco-svitol** [comment]
Sorry I didn't reply but I read your message.
I went for a walk!
Take your time, no rush.
Let me know if you need any further input.

**Comment by dudi2022** [comment]
Hey! No worries! I have been thinking about the issues but not working on
them. Pop-up is fine, I have a question about the query string.

You want it to be that when “Nome” the standard entry is selected, the
query string returns a standard code which is not Nome? This way the back
end can identify when nothing has been selected.

Is this a correct explanation of the task? Do you want the same if “random”
is entered into the drop down menus?

Thank you and have a great week. I will try and complete these tasks in the
evenings 👍

**Comment by dudi2022** [comment]
Ciao Marco!

Understood, so each option in the dropdown has four specific codes, or just
one? And how do I know which codes these should be for each option? Should
I just invent them for now or is there somewhere I can look for this data?

I haven't had a chance to look at the project yesterday or tonight... But
tomorrow I will finish a bit early and will be able to work on these issues.

Wishing you all the best,

Will

**Comment by marco-svitol** [comment]
Hey Will!
Each option has its own code (sorry I see now that I put a code beside "Nome" that should not be there...):
Freno = A91
Motore = A55
Trasmissione = F91

You can invent the codes, as we should get them from Guido.

take your time.

Buona giornata!
ciao

**Comment by dudi2022** [comment]
Got it, thank you for the explanations, Marco!

I will start working on this tomorrow evening :-)

Buona giornata, ciao!

Am Di., 7. Feb. 2023 um 09:46 Uhr schrieb Marco ***@***.***>:
