### ISSUE TITLE
Popup window to show document details (=abstract)

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#16]
When clicking on a row of the results (any column except the URL one), an "overaly" windows should pop up, showing the "document title" and the "abstract":
![image](https://user-images.githubusercontent.com/62987024/216783740-12bb48d7-3363-41f6-9629-b522b00f839d.png)
 
The window can be closed by clicking on the "Chiudi" button or -if possible- anywhere outside the window (clicking on the background).

**Comment by dudi2022** [comment]
Doable - just need to discuss how I will source the abstract data. Maybe a
brief call this afternoon if you have time?

**Comment by marco-svitol** [comment]
Sure, can we just do it early after lunch? Around 14?

**Comment by marco-svitol** [comment]
Anyway, the "abstract" field is already in the Json I send you in the search results.

**Comment by dudi2022** [comment]
Ah, got it! I will give this issue a go first, and then follow with the other issue.

**Comment by dudi2022** [comment]
need to complete the click outside to close and make sure the pop up is fully responsive on small screens (button position)

**Comment by dudi2022** [comment]
I can see the Searchbox inputs are still not aligned on my phone. Will fix ASAP.
