### ISSUE TITLE
When "date" field is missing the query string is wrong

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#20]
When you don't check the "date" checkbox, the query string sent to the backend is:
/api/v1/search&ti=Quantum

with a wrong "&" char. So the backend respond with a "404" not found.

The correct query should have a "?" char:
i.e.:
/api/v1/search?pdfrom=20230101&pdto=20230120&ti=Quantum

**Comment by marco-svitol** [comment]
suggestion:

    let queryString = "?";
    if (selectedOption === "titolo" && titolo) {
      queryString += "ti=" + titolo}
    else if (selectedOption === "area-tecnica" && areaTecnica) {
      switch (areaTecnica) {
        case "freno":
          queryString += "tecarea=A91";
          break;
        case "motore":
          queryString += "tecarea=A55";
          break;
        case "trasmissione":
          queryString += "tecarea=F91";
          break;
        default:
          break;
      }
    }
    if (includeDates && dataFrom && dataTo) {
      queryString +=
        "&pdfrom=" +
        moment(dataFrom).format("YYYYMMDD") +
        "&pdto=" +
        moment(dataTo).format("YYYYMMDD");
    }
    if (testo) queryString += "&txt=" + testo;

**Comment by dudi2022** [comment]
your solution has been implemented :-D cheers!
