### ISSUE TITLE
Create Read, Unread and New Categories for Patents

### ISSUE THREAD

**Issue by dudi2022** [marco-svitol/quaestio-fe#24]
Information to be provided by the backend, and should then be displayed in a user-friendly way.

**Comment by marco-svitol** [comment]
_Just for testing_ I am now sending you random status values.
You can already try it out.


To send you the information if a document was opened, I need you to send me a notification about that.
So we should introduce a new API that you will call whenever a user open a docs.

I will create a new section in the API documentation as well and then come back to this issue.

**Comment by marco-svitol** [comment]
I think we should move the "LinkOPS" inside the "Preview Box".
Otherwise it would be hard to track when a user opens the document through the OPS Link.

I suggest that we provide a preview in first place and the "Link OPS" as a deepr dive.
When a user clicks on the row you will open the preview (as doing now) but you will also -at the same time- send me a notification to an agreed API endpoint.
What do you think?

**Comment by dudi2022** [comment]
got it - this went through my mind too - thanks for the clarification!

Am Do., 20. Apr. 2023 um 19:21 Uhr schrieb Marco ***@***.***>:

**Comment by dudi2022** [comment]
The colours can be improved but it's functioning on my end:

[image: image.png]

Am Do., 20. Apr. 2023 um 19:39 Uhr schrieb William Beatty <
***@***.***>:

**Comment by marco-svitol** [comment]
Yes, it works. 
On my browser I see an empty column on the right of the table. Is it for purpose?
![image](https://user-images.githubusercontent.com/62987024/233450912-0999a5f1-2ab2-413e-906c-ff74569e2061.png)

**Comment by marco-svitol** [comment]
Developing the "opendoc" API:
https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-opendoc--returns-url-to-ops-original-doc

I will return you the URL to the OPS doc and remove it from the "search" API response

**Comment by dudi2022** [comment]
Hey I’m out right now will get back on the project later / tomorrow and
resolve these issues 👍

Ciaoooo

**Comment by marco-svitol** [comment]
yeppp. enjoy!
ciaoooo

Il giorno gio 20 apr 2023 alle ore 20:59 dudi2022 ***@***.***>
ha scritto:

> Hey I’m out right now will get back on the project later / tomorrow and
> resolve these issues 👍
>
> Ciaoooo
>

**Comment by dudi2022** [comment]
thank you! column is fixed, small screens is messy now but I'm too tired to
solve it - tomorrow & weekend.

I will follow your new documentation to create the opendoc call then also
:-) ciaooo

Am Do., 20. Apr. 2023 um 21:40 Uhr schrieb Marco ***@***.***>:

> yeppp. enjoy!
> ciaoooo
>
> Il giorno gio 20 apr 2023 alle ore 20:59 dudi2022 ***@***.***>
> ha scritto:
>
> > Hey I’m out right now will get back on the project later / tomorrow and
> > resolve these issues 👍
> >
> > Ciaoooo
> >

**Comment by dudi2022** [comment]
Ciao Marco, I hope you're well.

Is this the right url? https://quaestio-be.azurewebsites.net/api/v1/opendoc

**Comment by marco-svitol** [comment]
hi Will I am fine thanks. Went out to take some air...this full smartworking is kinda killing me 🥵

The url is correct, but I am not sure if I have already merged, in few minutes I ll check and update you

**Comment by dudi2022** [comment]
thanks for the heads up, Marco!

my gosh... hope you can take it easy this weekend!

I will come back to this tomorrow - I'm getting an error 404 right now.

Ciao :-)


Am Fr., 21. Apr. 2023 um 20:21 Uhr schrieb Marco ***@***.***>:

**Comment by dudi2022** [comment]
Ciao Marco!

I have implemented solutions on FE for the dynamic dropdown filling and the
modal api call.

for dynamic, i have an error 401
for modal, i have error 404

maybe we can troubleshoot this together sometime before I try to solve it
alone :-)

Am Fr., 21. Apr. 2023 um 22:28 Uhr schrieb William Beatty <
***@***.***>:

**Comment by marco-svitol** [comment]
Buongiorno Will!

Merging yours and also mine with opendoc API. Notice that I'm still sending you random values for "read_history".


-> Sure I am available this morning. Just ping me on whatsapp or mail when you're ready

**Comment by marco-svitol** [comment]
The 404 should be fixed now by my latst merge.

For the 401 I think you're missing the uid on the request:
![image](https://user-images.githubusercontent.com/62987024/233772821-bd0cca4b-460c-46ea-9148-d7246d55e0bb.png)

**Comment by marco-svitol** [comment]
Merged first working version of doc status APIs in backend. Let's give it a try.

**Comment by marco-svitol** [comment]
tested. ok
