### ISSUE TITLE
Please review UI and API specs

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#27]
Ciao dudi2022 :)

Please have a look at the API documentation [here](https://github.com/marco-svitol/quaestio-be/wiki/API-implementation)

and at the UI description [here](https://github.com/marco-svitol/quaestio-fe/wiki/Appearance)

I've not yet implemented the API methods, I would do it next week.
Meanwhile tell me if it's all clear and if  there is any error.

Once you read the docs we can close this issue.

**Comment by dudi2022** [comment]
Ciao Marco, I'm starting to implement, but I am unsure what url I should use for the login process. Please could you let me know!

**Comment by marco-svitol** [comment]
ciao Will
You should use the standard one:

https://quaestio-be.azurewebsites.net

API call would be:

https://quaestio-be.azurewebsites.net/api/v1/auth/login?username=USERNAME&password=PASSWORD

**Comment by dudi2022** [comment]
Perfect, thank you so much!

I understand now that this is the standard API link. I will work on it as
soon as I'm free from work today!

Ciao

Am Di., 18. Apr. 2023 um 12:09 Uhr schrieb Marco ***@***.***>:
