### ISSUE TITLE
Fill Search Page drop-down lists dynamically 

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#30]
userprofile API is ready: fill the "applicant" drop down list (in italian ="Richiedente" ) and the tecarea drop down list with dynamic values, retrieved from the backend using the API as described in the Wiki:
https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-userprofile--returns-users-relevant-data-to-prepare-the-search-page

**Comment by dudi2022** [comment]
solution attempted on frontend but getting 401 unauthorised from backend

<img width="246" alt="image" src="https://user-images.githubusercontent.com/117585593/233764997-d6b48c3b-5a39-4a11-9b95-d26943c39647.png">

**Comment by marco-svitol** [comment]
tested ok. closing
