### ISSUE TITLE
Search page: change DropDown list "Titolo" to "Richiedente"

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#31]
Please fix the title and update the corresponding query field with "pa" instead of "ti".

Example:
  Search box values:
    Richiedente = "Emmet Brown"
    Testo = "Time Machine"
    Data = dal 05/11/1955 al 5/11/1985

API call:
https://quaestio-be.azurewebsites.net/api/v1/search?ap=Emmet Brown&txt=Time Machine&pdfrom=19551105&pdto=19851105

**Comment by dudi2022** [comment]
Hey Marco!

In the sentence, you ask for "pa" but in the query you have "ap".

Which one should I do?

Best

**Comment by dudi2022** [comment]
for now i have done "pa"

**Comment by marco-svitol** [comment]
pa is correct. Oppps 😐
