### ISSUE TITLE
Keep the selected search values after showing the results

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#61]
Would be nice if we could keep the search values instead of resetting the boxes to empty values.
![image](https://user-images.githubusercontent.com/62987024/234317896-92b9b09e-08b1-45a3-abb1-66867b49d321.png)

Afer the search (actual):
![image](https://user-images.githubusercontent.com/62987024/234318485-3fccf111-2d74-42dc-8f03-af6c19e4313e.png)

After the search (desired):
![image](https://user-images.githubusercontent.com/62987024/234318751-e470a3e8-05ae-4d89-9e19-732cf6d0bdf7.png)

**Comment by dudi2022** [comment]
done
