### ISSUE TITLE
Search results table position

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#7]
The result table sometimes shows up in a wrong position.
i.e: with these search parameters:
![image](https://user-images.githubusercontent.com/62987024/215419800-178122a9-c7c9-4dd5-8576-d794a5d41e39.png)

you get:
![image](https://user-images.githubusercontent.com/62987024/215419890-99dddd61-7e6e-4d54-8266-b72c2ff0d636.png)

**Comment by dudi2022** [comment]
Will fix ASAP

**Comment by dudi2022** [comment]
solved
