### ISSUE TITLE
Show throttling info

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#71]
In the Search API (https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-search--search-patent-documents)
together with the results, I am also returning userinfo.throttling-control.

We should print this info in the browser console log.

If the API sends you this:
```
    {
        "userinfo": {
            "throttling-control": [
                [
                    "idle"
                ],
                [
                    "images",
                    "green:200"
                ],
                [
                    "inpadoc",
                    "green:60,"
                ],
                [
                    "other",
                    "green:1000,"
                ],
                [
                    "retrieval",
                    "green:200,"
                ],
                [
                    "search",
                    "green:30"
                ]
            ],
            "individualquotaperhour-used": "541368",
            "registeredquotaperweek-used": "1567113"
        }
    }
```

you should shrink into a one-line in the console:
`idle,images:green:200,inpadoc:green:60,other:green:1000,retrieval:green:200,search:green:30,individualquotaperhour-used:541368,registeredquotaperweek-used:1567113`

**Comment by dudi2022** [comment]
solution implemented-check together

**Comment by dudi2022** [comment]
done
