### ISSUE TITLE
show exemplary image in modal window

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#75]
This issue depends on marco-svitol/quaestio-be/issues/45

**Comment by marco-svitol** [comment]
> This issue depends on [marco-svitol/quaestio-be/issues/45](https://github.com/marco-svitol/quaestio-be/issues/45)

Issue completed. You should proceed by using updated API Wiki doc:
check [here](https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-opendoc--returns-url-to-ops-original-doc-and-list-of-available-images-drawings)
and [here](https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-firstpageclipping--returns-the-modal-image)

**Comment by dudi2022** [comment]
Ok! Thank you! I have a busy day but will get to it as soon as possible.

**Comment by dudi2022** [comment]
here so far...
<img width="223" alt="image" src="https://github.com/marco-svitol/quaestio-fe/assets/117585593/b7c5849d-ee74-49b8-a472-0c61cf16eba8">
<img width="403" alt="image" src="https://github.com/marco-svitol/quaestio-fe/assets/117585593/6ad5111a-1f62-429b-a454-fb332cd4746a">
sorry, I did not achieve it tonight! made many structural changes to app.js though...

**Comment by dudi2022** [comment]
resolved with some warnings

<img width="235" alt="image" src="https://github.com/marco-svitol/quaestio-fe/assets/117585593/292e4d07-885b-46bf-a7c7-2c1301a08b4b">
![Uploading image.png…]()

**Comment by dudi2022** [comment]
<img width="972" alt="image" src="https://github.com/marco-svitol/quaestio-fe/assets/117585593/4a3cca1f-ed59-49f9-964a-e278f3beb7a4">

**Comment by marco-svitol** [comment]
left some comments on the PR

**Comment by marco-svitol** [comment]
you rock! fixed!
