### ISSUE TITLE
API userprofile and search version 2

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#78]
I've slightly changed the backend logic on how the queries to OPS are created to hide the "added value" from the public and store them in db.

This requires a change also on your side.

Please first chek the documentation for version 2 of the APIs:
userprofile: [ver. 2](https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-userprofile--returns-users-relevant-data-to-prepare-the-search-page-1)
search: [ver. 2](https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-search--search-patent-documents-1)

You will call ver.2 of APIs _userprofile_ and _search_ by changing the path prefix : /api/v2 

Version 2 of the APIs is working only with user acme (will send you the password by mail).

All the others API calls should not be changed.

Once you've succesfully implemented the changes and we merge your code I will remove version 1.

This is quite a new process of delivering, so please feel free to reach me out for clarifications in case.
ciao!

**Comment by dudi2022** [comment]
Ok! I will look at it and make the changes asap

**Comment by dudi2022** [comment]
done
