### ISSUE TITLE
Show logo image

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#79]
coming soon....

**Comment by marco-svitol** [comment]
In the response of userprofile API, there is a new field:
userinfo.logopath

check Wiki:
https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-userprofile--returns-users-relevant-data-to-prepare-the-search-page

You can visualize the logo file in the toolbar for example or wherever you think.

**Comment by dudi2022** [comment]
included in searchbox for now

**Comment by dudi2022** [comment]
in navbar
