### ISSUE TITLE
Pagination improvement

### ISSUE THREAD

**Issue by marco-svitol** [marco-svitol/quaestio-fe#81]
Currently the pagination is based on the total number of results returned by the Search API.

In the resutls of the search API version2 you now have an extra section called "resultsInfo": check [wiki](https://github.com/marco-svitol/quaestio-be/wiki/API-implementation#get-search--search-patent-documents-1)

Search ver.2 has also a new optional parameter called "beginRange".

With this info and the new parameter you should create a dynamic pagination:
1. after the first call to search api, if you specify the "beginRange=1", you will not receive all the available results from the backend (as it was doing before), but only the first 12 results.
2. You will show the first 12 results results on page 1 and build the list of available pages (between the arrows) using the total result count. i.e. If total results is = 280 you will show the pages numbers from 1 to 24. (on page 24 only 4 results will be retrieved -> 280 = 23*12 + 4).
3. Each page should have a link to a search api with the beginRange parameter = (number of the page * 12 + 1). ie. The link of page 18 would be https://endpoint.api.com/api/v2/search?tecarea=2&uid=1&pdfrom=20230420&pdto=20230520&beginRange=217

Notice that the "beginRange" is optional: if you don't specify it, you will now receive a fixed number of 50 results. This is to keep retro-compatibility.

In a future implementation the static "12 results per page" will be customizable per user.

**Comment by marco-svitol** [comment]
And here is the beautified ChatGPT version :)


Dear,

I would like to bring to your attention the current state of pagination in our system, specifically in relation to the Search API. Currently, pagination is based on the total number of results returned by the API.

I am pleased to inform you that with the introduction of Search API version 2, we have made some significant enhancements. One notable addition is the inclusion of an extra section called "resultsInfo." For more detailed information on this, please refer to the documentation available on our wiki.

Moreover, Search API version 2 introduces a new optional parameter called "beginRange." This parameter plays a crucial role in enabling dynamic pagination. Here's how it works:

After making the initial call to the Search API, if you specify "beginRange=1," you will no longer receive all the available results from the backend as was the case previously. Instead, you will only receive the first 12 results. These initial results should be displayed on page 1, and a list of available pages should be generated using the total result count. To illustrate, if the total number of results is 280, you should display the page numbers from 1 to 24. On page 24, only 4 results will be retrieved (280 = 23 * 12 + 4).

For each page, there should be a corresponding link to the Search API with the "beginRange" parameter set to (page number * 12 + 1). For example, the link for page 18 would be:
https://endpoint.api.com/api/v2/search?tecarea=2&uid=1&pdfrom=20230420&pdto=20230520&beginRange=217

Please note that the "beginRange" parameter is optional. If not specified, a fixed number of 50 results will be returned. This is done to ensure backward compatibility with existing implementations.

I would also like to inform you that in a future update, we plan to make the static "12 results per page" customizable on a per-user basis.

Thank you for your attention to this matter. If you have any further questions or require additional clarification, please don't hesitate to reach out.

**Comment by dudi2022** [comment]
Haha nice!

I'm still messing around with this - will implement as soon as I can!

Just to confirm, the correct link is:
https://endpoint.api.com/api/v2/search?tecarea=2&uid=1&pdfrom=20230420&pdto=20230520&beginRange=217
or
is endpoint.api.com
<https://endpoint.api.com/api/v2/search?tecarea=2&uid=1&pdfrom=20230420&pdto=20230520&beginRange=217>
replaced
with the existing quaestio-be.azurewebsites.net - ?

Have a great day!

Am Fr., 26. Mai 2023 um 20:21 Uhr schrieb Marco ***@***.***>:

**Comment by marco-svitol** [comment]
Buongiorno Will,
the second one is correct:  quaestio-be.azurewebsites.net .

Because the Wiki page is public, I don't want to use our actual values for
the examples.
Sorry for the confusion.

Nice job with the other issues! thanks!

ciao!
Marco

Il giorno lun 29 mag 2023 alle ore 08:50 Will ***@***.***> ha
scritto:

**Comment by dudi2022** [comment]
Got it, I thought so!

Understood, I will get on the issue soon; it's the craziest weeks of the
year for us so might have a little delay.

Yes, it was a big surprise when suddenly the new version worked! very
happy!!

Vi auguro una buona giornata!

Am Mo., 29. Mai 2023 um 09:23 Uhr schrieb Marco ***@***.***>:

**Comment by marco-svitol** [comment]
No worries at all.
We are perfectly on track.
a presto!
buona giornata!

Il giorno lun 29 mag 2023 alle ore 09:37 Will ***@***.***> ha
scritto:
