### ISSUE TITLE
no API data

### ISSUE THREAD

**Issue by dudi2022** [marco-svitol/quaestio-fe#9]
not sure if its because of the changes i just made or if you are working on the backend. 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/117585593/215570554-e0d9550d-e7bc-459c-ab10-c54f71140387.png">

**Comment by dudi2022** [comment]
need data to see table & adjust margin/madding (#7)

**Comment by marco-svitol** [comment]
The backend was crashed. I had to restart it manually. 
I may have found the bug and now I have pushed the fixes.
Will also try to configure an autoresart in case of crash.
